version: '3'
services:
  gym_management_backend:
    image: gym_management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./target:/app/target # This mounts your local target folder into the container
    restart: always
